{{/*
 Copyright (c) Facebook, Inc. and its affiliates.

 This source code is licensed under the MIT license found in the
 LICENSE file in the root directory of this source tree.
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-edge-hub
  labels:
    app.kubernetes.io/component: prometheus-edge-hub
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus-edge-hub
  template:
    metadata:
      labels:
        app.kubernetes.io/component: prometheus-edge-hub
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | trimSuffix "\n" | indent 8 }}
      {{- end }}

      containers:
        - name: "prometheus-edge-hub"
          image: {{ required "image.repository must be provided" .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          args: ["-limit={{ .Values.limit }}",
                 "-port={{ .Values.port }}",
                 "-scrapeTimeout={{ .Values.scrapeTimeout }}"]
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
{{ toYaml .Values.resources | indent 12 }}
