{{/*
 Copyright (c) Facebook, Inc. and its affiliates.

 This source code is licensed under the MIT license found in the
 LICENSE file in the root directory of this source tree.
*/}}
apiVersion: v1
kind: Service
metadata:
  name: prometheus-edge-hub
  labels:
    app.kubernetes.io/component: prometheus-edge-hub
    {{- with .Values.service.labels }}
{{ toYaml . | indent 4}}
    {{- end}}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4}}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: prometheus-edge-hub
  type: {{ .Values.service.type }}
  ports:
{{- range $port := .Values.service.ports }}
     - name: {{ $port.name }}
       port: {{ $port.port }}
       targetPort: {{ $port.targetPort }}
{{- end }}
{{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end -}}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
{{- end -}}
